name = "gacha-wiki"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
compatibility_date = "2024-01-01"

[vars]
NODE_VERSION = "20"

[[redirects]]
from = "/http-version"
to = "/"
status = 301

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.{woff2,woff,png,jpg,jpeg,gif,svg,webp,avif,ico}"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"