import fs from 'fs';
import path from 'path';

const BASE = 'C:/Users/Borin/OneDrive/Documents/gacha-wiki/src/data/busty-burst/characters';

const charFiles = fs.readdirSync(BASE).filter(f => f !== 'index.js' && f.endsWith('.js'));
const results = charFiles.map(f => {
  const slug = f.replace('.js', '');
  const content = fs.readFileSync(path.join(BASE, f), 'utf-8');
  return { slug, hasInfo: content.includes('export const info'), hasSkills: content.includes('export const skills'), hasStats: content.includes('export const stats') };
});

function safeName(s) { return s.replace(/-/g, '_'); }

let indexContent = '// Character data registry - auto-generated by scripts/migrate-bb-data.js\n// Do not edit manually\n\n';

indexContent += results.map(r => {
  const s = safeName(r.slug);
  const imports = [];
  if (r.hasInfo) imports.push(`info as ${s}_info`);
  if (r.hasSkills) imports.push(`skills as ${s}_skills`);
  if (r.hasStats) imports.push(`stats as ${s}_stats`);
  return `import { ${imports.join(', ')} } from "./${r.slug}.js";`;
}).join('\n') + '\n\n';

const infoSlugs = results.filter(r => r.hasInfo);
const skillsSlugs = results.filter(r => r.hasSkills);
const statsSlugs = results.filter(r => r.hasStats);

indexContent += `export const BUSTY_BURST_CHARACTER_INFO = {\n${infoSlugs.map(r => `  "${r.slug}": ${safeName(r.slug)}_info,`).join('\n')}\n};\n\n`;

indexContent += `export const BUSTY_BURST_CHARACTER_STATS = {\n${statsSlugs.map(r => `  "${r.slug}": ${safeName(r.slug)}_stats,`).join('\n')}\n};\n\n`;

indexContent += `export const BUSTY_BURST_SKILLS_DATA = [\n${skillsSlugs.map(r => `  ${safeName(r.slug)}_skills,`).join('\n')}\n].filter(Boolean);\n\n`;

indexContent += `export function getAllCharacters() {\n  return Object.values(BUSTY_BURST_CHARACTER_INFO);\n}\n\n`;
indexContent += `export function getCharacterBySlug(slug) {\n  return BUSTY_BURST_CHARACTER_INFO[slug] || null;\n}\n\n`;
indexContent += `export function getAllCharacterSlugs() {\n  return Object.keys(BUSTY_BURST_CHARACTER_INFO);\n}\n\n`;
indexContent += `export function getAllCharacterStats() {\n  return Object.values(BUSTY_BURST_CHARACTER_STATS);\n}\n\n`;
indexContent += `export function getCharacterStatsById(id) {\n  return BUSTY_BURST_CHARACTER_STATS[id] || null;\n}\n\n`;
indexContent += `export function getCharacterStatsByCharacterId(characterId) {\n  return Object.values(BUSTY_BURST_CHARACTER_STATS).find(c => c.characterId === characterId) || null;\n}\n\n`;

indexContent += `export function calculateStatAtLevel(base, lv90, level) {\n  if (level <= 1) return base;\n  if (level >= 90) return lv90;\n  const growth = lv90 - base;\n  const perLevel = growth / 89;\n  return Math.floor(base + perLevel * (level - 1));\n}\n\n`;

indexContent += `export function calculateCritRate(critValue) {\n  return (critValue / 20).toFixed(2);\n}\n\n`;

indexContent += `export const STAT_DISPLAY_NAMES = {\n  hp: 'HP', atk: 'ATK', matk: 'MATK', def: 'DEF', mdef: 'MDEF',\n  accuracy: 'Accuracy', block: 'Block', physCrit: 'Crit Rate',\n  magicCrit: 'M.Crit Rate', hpRegen: 'HP Regen', mpRegen: 'MP Charge',\n  healPwr: 'Heal Pwr', mpCharge: 'MP Charge', hpDrain: 'HP Drain',\n  mpCostDown: 'MP Cost',\n  'HP': 'HP', 'ATK': 'ATK', 'MATK': 'MATK', 'DEF': 'DEF', 'MDEF': 'MDEF',\n  'Accuracy': 'Accuracy', 'Block': 'Block', 'Phys Crit': 'Crit Rate',\n  'Magic Crit': 'M.Crit Rate', 'HP Regen': 'HP Regen', 'MP Regen': 'MP Charge',\n  'Heal Pwr': 'Heal Pwr', 'MP Charge': 'MP Charge', 'HP Drain': 'HP Drain',\n  'MP Cost Down': 'MP Cost',\n};\n\n`;

indexContent += `export const SPEED_LABELS = {\n  'Very Fast': { label: 'Very Fast', freezeTime: '0.36s' },\n  'Fast': { label: 'Fast', freezeTime: '0.61s' },\n  'Slightly Fast': { label: 'Slightly Fast', freezeTime: '0.69s' },\n  'Normal': { label: 'Normal', freezeTime: '0.86s' },\n  'Slightly Slow': { label: 'Slightly Slow', freezeTime: '1.00s' },\n  'Slow': { label: 'Slow', freezeTime: '1.11s' },\n  'Very Slow': { label: 'Very Slow', freezeTime: '1.36s' },\n};\n\n`;

indexContent += `export const STATUS_EFFECTS = {\n  'Petrify': 'Cannot act, Block rate becomes 0',\n  'Stun': 'Cannot act',\n  'Freeze': 'Cannot act, receives damage over time',\n  'Sleep': 'Cannot act, wakes up when hit by a critical attack',\n  'Silence': 'Cannot use skills or ultimate',\n  'Confusion': 'Attacks random targets',\n  'Charm': 'Attacks own allies',\n  'Taunt': 'Forces target to attack the taunter',\n  'Poison': 'Receives damage over time',\n  'Burn': 'Receives damage over time (stackable)',\n  'Bleed': 'Receives damage over time (-1% HP)',\n  'Paralysis': 'Speed -50%, Attack -50%',\n  'Curse': 'Cannot recover, Speed -50%, Critical rate becomes 0',\n  'Blind': 'Block rate becomes 0, Accuracy -50%',\n  'Fear': 'MP is drained over time',\n};\n\n`;

indexContent += `export const BUFF_LEVELS = {\n  'ATK+': { Lv1: '+10%', Lv2: '+15%', Lv3: '+20%', Lv4: '+25%', LvMax: '+30%' },\n  'DEF+': { Lv1: '+10%', Lv2: '+15%', Lv3: '+20%', Lv4: '+25%', LvMax: '+30%' },\n};\n`;

fs.writeFileSync(path.join(BASE, 'index.js'), indexContent, 'utf-8');
console.log(`Regenerated index.js`);
console.log(`  Total: ${results.length} chars, Info: ${infoSlugs.length}, Skills: ${skillsSlugs.length}, Stats: ${statsSlugs.length}`);
