name: Discord Notification

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        
    - name: Get commit info
      id: commit
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
        COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
        COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
        
        echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
        echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
        echo "url=$COMMIT_URL" >> $GITHUB_OUTPUT
        echo "short_sha=$COMMIT_SHORT_SHA" >> $GITHUB_OUTPUT
        
    - name: Send Discord notification
      if: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
               "embeds": [{
                 "title": "🚀 New push to Gacha Wiki",
                 "description": "**Commit:** [${{ steps.commit.outputs.short_sha }}](${{ steps.commit.outputs.url }})\n**Author:** ${{ steps.commit.outputs.author }}\n**Message:** ${{ steps.commit.outputs.message }}\n**Branch:** ${{ github.ref_name }}",
                 "color": 3447003,
                 "footer": {
                   "text": "Gacha Wiki • gachawiki.info"
                 },
                 "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)'"
               }]
             }' \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
             
    - name: Send simple fallback notification
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content": "📝 New commit `${{ steps.commit.outputs.short_sha }}` by **${{ steps.commit.outputs.author }}** - ${{ steps.commit.outputs.message }}"}' \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
      continue-on-error: true