name: Discord Notification

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        if [ -z "$DISCORD_WEBHOOK_URL" ]; then
          echo "DISCORD_WEBHOOK_URL secret not set"
          exit 1
        fi
        
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content": "🚀 **New push to Gacha Wiki!**\n\n**Commit:** `'"${{ github.sha }}"'`\n**Author:** '"${{ github.actor }}"'\n**Branch:** '"${{ github.ref_name }}"'\n**Repository:** '"${{ github.repository }}"'\n\n[View commit](https://github.com/'"${{ github.repository }}"'/commit/'"${{ github.sha }}"')"}' \
             "$DISCORD_WEBHOOK_URL"